version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=jottom
      - MARIADB_DATABASE=jottom_laravel
  laravel:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=jottom
      - DB_DATABASE=jottom_laravel
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
